### PR TITLE
Sebastian/clang format

### PR DESCRIPTION
**Pull request by sebwolf-de**
Hi,

after we have done the merge of the xml branch, I've experimented with clang-format to enforce a common coding style.
Coding style is LLVM, I've configured it such that a merge is impossible without fulfilling the coding style.
I've reformated the existing code base. Starting from git 2.23 you can use `git blame --ignore-revs-file .git-blame-ignore-revs src/pumgen.cpp` to get a clean git blame output.

### CODE REVIEW

**Comment by krenzland** [comment]
In principle, I like this a lot but the exact code style is of course a point of great debate...

**Comment by uphoffc** [comment]
I like this one:
https://github.com/TEAR-ERC/mneme/blob/master/.clang-format

**Comment by uphoffc** [comment]
Where is the .clang-format file in this PR?

**Comment by krenzland** [comment]
@uphoffc I wanted to disagree with your recommendation on principle. Luckily, I noticed that I pushed the clang-format. So, it's of course the best option.

(Kidding aside, it's a good set of defaults and at least one project that is going to get integrated into SeisSol uses it already!)

**Comment by sebwolf-de** [comment]
You can run clang-format without a .clang-format file. Then it's LLVM style.

**Comment by krenzland** [comment]
I'd advise against that. The default styles can change, better to make the explicit. The file Carsten recommended is basically an export of the LLVM style with some minor tweaks (if I remember correctly).

**Comment by uphoffc** [comment]
Yes, it has 100 chars per line instead of 80 chars per line, which makes totally sense for widescreen laptops :) 

I would also recommend to put the style there. Some tools search recursively upwards for a clang-format file and I leave it to your imagination what happens if it's missing.

**Comment by Thomas-Ulrich** [comment]
Let's suppose we have a branch which is very old with things we would like to port to master.
(e.g.  carsten/energy_output on SeisSol/SeisSol). Don't you think it would be a mess to figure out what's new and what's have been reformated, and then merging the changes is even more complicated than before?
That being said, I don't think we have this problem on Seisol/Pumgen.

**Comment by krenzland** [comment]
The way would then be to format that branch as well and then merge it. Not ideal though.

That's why trying with pumgen is a good idea, there's not much that can go wrong.

**Comment by Thomas-Ulrich** [comment]
That being said, I m not a big fan of the 100 char limit, e.g.
https://github.com/SeisSol/PUMGen/blob/sebastian/clang-format/src/input/MeshAttributes.cpp#L30
on my laptop screen, I would have twice that space available.

**Comment by uphoffc** [comment]
So the 100 char limit let's you see one line completely on a half screen (16:9 screen). I often code in a half screen window and use the other half for something else (Browser, Paper, etc ...)

**Comment by sebwolf-de** [comment]
How many chars fit one screen depends on your zoom level and other personal preferences. I see that the classic 80 are too little. Anyhow having very long lines makes code unreadable.

**Comment by Thomas-Ulrich** [comment]
Ok, I would use a large line number, but I understand your arguments, and it is not a big deal.
Then we should adapt and write smaller variable names ;-)

**Comment by krenzland** [comment]
@ravil-mobile mentioned doubts regarding the alignment: The clang format specifies 4 spaces whilst we use mainly 2 in seissol.

**Comment by krenzland** [comment]
There is now a related issue: #23.

**Comment by sebwolf-de** [comment]
We can agree on an indent of 2. No problem.
About the line lenght: Using half of the monitor my terminal is 118 characters wide. Balancing between @uphoffc, who want's to use half his monitor for coding and the other half for something else and @Thomas-Ulrich, who prefers longest possible lines, I propose a character limit of 110 per line. Any objections?

**Comment by krenzland** [comment]
I think that 100 is a good number. The max. line length in my clion (if split in two panels) is roughly 105.
If in doubt I'd steer towards the smaller number -> shorter lines are easier to read (actually backed up by science afaik)

**Comment by sebwolf-de** [comment]
Since there haven't been any objections in the past two weeks, I'll merge this.

**Pull request merged**
